// workspaces/www.monalisatalk-fan.site/src/components/YouTubeThumbnail.svelte
<script context="module" lang="ts">
  let cache: Record<string, HTMLImageElement | undefined> = {};
</script>

<script lang="ts">
  import { onMount } from 'svelte';

  /** ビデオのID */
  export let videoId: string;

  /** クオリティ */
  export let size: 'default' | 'hqdefault' | 'maxresdefault' = 'hqdefault';

  let src: string;
  let canvasElement: HTMLCanvasElement | null;

  onMount(() => {
    const imageSource = `//img.youtube.com/vi/${videoId}/${size}.jpg`;
    const cachedImage = cache[imageSource];

    /** サムネイルを Canvas に描画する */
    const drawThumbnail = (img: HTMLImageElement) => {
      if (!canvasElement) {
        src = imageSource;

        return;
      }

      const ctx = canvasElement.getContext('2d');

      if (!ctx) {
        src = imageSource;

        return;
      }

      canvasElement.width = img.naturalWidth;
      canvasElement.height = img.naturalHeight;

      ctx.drawImage(img, 0, 0);
    };

    if (cachedImage) {
      drawThumbnail(cachedImage);

      return;
    }

    const img = new Image();

    img.onload = () => {
      drawThumbnail(img);

      cache = {
        ...cache,
        [imageSource]: img,
      };
    };

    img.onerror = () => {
      src = imageSource;
    };

    img.src = imageSource;
  });
</script>

<div class="youtubeThumbnail">
  {#if src}
    <img class="image" {src} alt="" />
  {:else}
    <canvas class="image" bind:this={canvasElement} />
  {/if}
</div>

<style lang="scss">
  .youtubeThumbnail {
    position: relative;

    &::before {
      display: block;
      width: 100%;
      padding-top: 56.25%;
      content: '';
    }

    & > .image {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      object-fit: cover;
      object-position: center;
    }
  }
</style>

// workspaces/www.monalisatalk-fan.site/components/YouTubeThumbnail/index.tsx
import React, { useEffect, useRef } from 'react';
import clsx from 'clsx';
import { useReactiveState } from '@lollipop-onl/react-reactive-state';
import styles from './index.module.css';
import { useContentVisibility } from '~/hooks/useContentVisibility';

export type Props = {
  videoId: string;
};

const cache: Map<string, HTMLImageElement> = new Map();

export const YouTubeThumbnail: React.VFC<Props> = ({ videoId }) => {
  const fallbackImageUrl = useReactiveState<string>();
  const isLoading = useReactiveState(true);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const { isContentVisible } = useContentVisibility(containerRef);

  useEffect(() => {
    const imageUrl = `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`;
    const cachedImage = cache.get(imageUrl);

    const drawThumbnail = (img: HTMLImageElement) => {
      if (!canvasRef.current) {
        isLoading.value = false;

        fallbackImageUrl.value = imageUrl;

        return;
      }

      const ctx = canvasRef.current.getContext('2d');

      if (!ctx) {
        isLoading.value = false;

        fallbackImageUrl.value = imageUrl;

        return;
      }

      canvasRef.current.width = img.naturalWidth;
      canvasRef.current.height = img.naturalHeight;

      ctx.drawImage(img, 0, 0);
    };

    if (cachedImage) {
      isLoading.value = false;

      drawThumbnail(cachedImage);

      return;
    }

    if (!isContentVisible) {
      return;
    }

    const img = new Image();

    img.onload = () => {
      isLoading.value = false;

      drawThumbnail(img);

      cache.set(imageUrl, img);
    };

    img.onerror = () => {
      isLoading.value = false;

      fallbackImageUrl.value = imageUrl;
    };

    img.src = imageUrl;
  }, [canvasRef, fallbackImageUrl, isLoading, isContentVisible, videoId]);

  return (
    <div className={styles.youtubeThumbnail} ref={containerRef}>
      {fallbackImageUrl.value ? (
        <img className={styles.image} src={fallbackImageUrl.value} />
      ) : (
        <canvas className={styles.image} ref={canvasRef} />
      )}
      <p className={clsx(styles.loading, isLoading.value && styles.Active)}>
        loading...
      </p>
    </div>
  );
};
